### ISSUE TITLE
Restart takes so much time after applying essential tweaks win10.

### ISSUE THREAD

**Issue by Fatvallon** [ChrisTitusTech/win10script#344] opened 2022-05-08 22:25 UTC
I'm using an ssd so restart usually takes few seconds but after applying essential tweaks i could confirm that it takes at least 3 minutes to restart and only restart that is broken, shutting down the windows is working normally.

I was only able to fix it when i restored the windows before applying the essential tweaks.

Any suggested solutions ?

**Comment by Carterpersall** [comment] 2022-05-09 04:47
Possible duplicate of #333, your solution is likely in there

**Comment by Fatvallon** [comment] 2022-05-09 07:47
I read it before posting mine also tried what was suggested like re-enabling Fast start option but it also does say that restart won't be affected anyway however i tried it and didn't help, also tried `powercfg /H off` and did not work, even undoing the tweaks didn't help only system restore which also revereted back all the tweaks that recovered the restart to the normal operation.

**Comment by Carterpersall** [comment] 2022-05-09 15:53
When looking through essential tweaks just now for anything that would affect restart speed, I found this section of code:
```
    Write-Host "Using regedit to improve RAM performance"

    Set-ItemProperty -Path "HKLM:\System\GameConfigStore" -Name "GameDVR_DXGIHonorFSEWindowsCompatible" -Type Hex -Value 00000000
    Set-ItemProperty -Path "HKLM:\System\GameConfigStore" -Name "GameDVR_HonorUserFSEBehaviorMode" -Type Hex -Value 00000000
    Set-ItemProperty -Path "HKLM:\System\GameConfigStore" -Name "GameDVR_EFSEFeatureFlags" -Type Hex -Value 00000000
    Set-ItemProperty -Path "HKLM:\System\GameConfigStore" -Name "GameDVR_Enabled" -Type DWord -Value 00000000
    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling" -Name "PowerThrottlingOff" -Type DWord -Value 00000001
    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Power" -Name "HiberbootEnabled" -Type DWord -Value 0000000
    Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching" -Name "SearchOrderConfig" -Type DWord -Value 00000000
    Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" -Name "SystemResponsiveness" -Type DWord -Value 0000000a
    Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" -Name "NetworkThrottlingIndex" -Type DWord -Value 0000000a
    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control" -Name "WaitToKillServiceTimeout" -Type DWord -Value 2000
    Set-ItemProperty -Path "HKLM:\Control Panel\Desktop" -Name "MenuShowDelay" -Type DWord -Value 0
    Set-ItemProperty -Path "HKLM:\Control Panel\Desktop" -Name "WaitToKillAppTimeout" -Type DWord -Value 5000
    Set-ItemProperty -Path "HKLM:\Control Panel\Desktop" -Name "HungAppTimeout" -Type DWord -Value 4000
    Set-ItemProperty -Path "HKLM:\Control Panel\Desktop" -Name "AutoEndTasks" -Type DWord -Value 1
    Set-ItemProperty -Path "HKLM:\Control Panel\Desktop" -Name "LowLevelHooksTimeout" -Type DWord -Value 00001000
    Set-ItemProperty -Path "HKLM:\Control Panel\Desktop" -Name "WaitToKillServiceTimeout" -Type DWord -Value 00002000
    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "ClearPageFileAtShutdown" -Type DWord -Value 00000001
    Set-ItemProperty -Path "HKLM:\SYSTEM\ControlSet001\Services\Ndu" -Name "Start" -Type DWord -Value 00000004
    Set-ItemProperty -Path "HKLM:\Control Panel\Mouse" -Name "MouseHoverTime" -Type DWord -Value 00000010
```
None of these are reverted in essentialundo for some reason (probably a bad pull request), and your problem might originate from here.
Theres a few things straight from here we can try right off the bat. 
1. Create a restore point and run the script again
2. Check if restart times are worse again
3. Try running these commands in an admin instance of PowerShell:
Set Time during shutdown/restart until Windows kills tasks back to the default of 5 seconds
```
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control" -Name "WaitToKillServiceTimeout" -Type DWord -Value 5000
Set-ItemProperty -Path "HKLM:\Control Panel\Desktop" -Name "WaitToKillServiceTimeout" -Type DWord -Value 00005000
```
Don't clear the pagefile at shutdown (shouldn't affect restarts but is worth a try)
```
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "ClearPageFileAtShutdown" -Type DWord -Value 00000000
```
4. If after running these and restarting your computer more than once the issue doesn't go away, revert back to the restore point and we can try a few more things.

**Comment by Fatvallon** [comment] 2022-05-09 19:09
ok thanks for the replies and here is the feedback,

this one applies normally
`Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control" -Name "WaitToKillServiceTimeout" -Type DWord -Value 5000`

`Set-ItemProperty -Path "HKLM:\Control Panel\Desktop" -Name "WaitToKillServiceTimeout" -Type DWord -Value 00005000`

give me the below error

```
Set-ItemProperty : Cannot find path 'HKLM:\Control Panel\Desktop' because it does not exist.
At line:1 char:1
+ Set-ItemProperty -Path "HKLM:\Control Panel\Desktop" -Name "WaitToKil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\Control Panel\Desktop:String) [Set-ItemProperty], ItemNotFoundExc
   eption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand
```
1. I tried multiple restarts after applying the tweaks and the restart time was affected again.
2. I applied the above 2 commands as illustrated and yet the issue still existed after also couple of restarts.

3. after applying `Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "ClearPageFileAtShutdown" -Type DWord -Value 00000000`
> This pretty much what solved the issue restart times are back to normal

I guess that's it then thanks a lot.

**Comment by Carterpersall** [comment] 2022-05-09 19:12
No problem! If you don't have any more questions, please close this issue to reduce clutter in the issues tab.

**Closed** 2022-05-09 19:12 UTC
