### ISSUE TITLE
Stuck on "Showing task manager details..."

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [ChrisTitusTech/win10script#302] opened 2022-03-14 18:12 UTC
Stuck on "Showing task manager details..." in 22572.1 build

**Comment by Carterpersall** [comment] 2022-03-20 03:49
Duplicate of #299 
The issue occurring to two different people like this means that this is likely not an isolated incident and is a real problem. If I get the time I'll look into it in a VM.

**Comment by SimPilotAdamT** [comment] 2022-03-20 11:40
Should be fixed in #304

**Closed** 2022-05-06 15:59 UTC
