### ISSUE TITLE
Installs browser hijacker to some random port that I cannot remove, disables windows search.

### ISSUE THREAD

**Issue by NOOBNOOBOX** [ChrisTitusTech/win10script#297] opened 2022-03-10 14:25 UTC
Installs browser hijacker none of the antivirus detects or finds any hijacker but still in my browser it shows that it is managed by organization after running the script. windows search also doesn't work after essential tweaks I did everything I could do, to fix it tried reinstalling windows search enabled Cortana, enabled background apps. Had to reinstall my windows installation.

**Comment by Carterpersall** [comment] 2022-03-11 14:29
Duplicate of #289 and #293 

It would be better for you to comment or react there instead of cluttering the issues tab with duplicates

**Comment by JustinT1188** [comment] 2022-03-12 12:33
I do not think that this is a browser hijack since it just disables a lot of Windows telemetry the way that Enterprise changes settings that is why a browser appears to have "Your browser is managed by your organization". Correct me I am right that your are using Microsoft Edge.

**Comment by Carterpersall** [comment] 2022-03-12 17:39
That is correct, ChrisTitus has stated several times before that that will happen if you use the script and run edge. He says that he does not recommend using the script if you use edge but I daily-drove edge for a long time with no issues so I would say contrary.

**Comment by NOOBNOOBOX** [comment] 2022-03-12 18:45
> Duplicate of #289 and #293
> 
> It would be better for you to comment or react there instead of cluttering the issues tab with duplicates

This is not a duplicate I had similar issue

**Comment by NOOBNOOBOX** [comment] 2022-03-12 18:47
> I do not think that this is a browser hijack since it just disables a lot of Windows telemetry the way that Enterprise changes settings that is why a browser appears to have "Your browser is managed by your organization". Correct me I am right that your are using Microsoft Edge.

No I am using Google Chrome.

**Comment by usrDottik** [comment] 2022-03-20 02:56
> I do not think that this is a browser hijack since it just disables a lot of Windows telemetry the way that Enterprise changes settings that is why a browser appears to have "Your browser is managed by your organization". Correct me I am right that your are using Microsoft Edge.

Fixing this is as easy as deleting some reg keys lol, it's not big deal really, I ran the script and I daily drive Chromium Edge, I just toggled with the reg key hive for it and it just works, you can pretty much search how to remove it googling it xd

**Comment by micziz** [comment] 2022-03-20 08:27
> Installs browser hijacker none of the antivirus detects or finds any hijacker but still in my browser it shows that it is managed by organization after running the script. windows search also doesn't work after essential tweaks I did everything I could do, to fix it tried reinstalling windows search enabled Cortana, enabled background apps. Had to reinstall my windows installation.

WELP, the script is for debating windows, and search is pretty telemetric, sooooo. You can use [open shell](https://github.com/Open-Shell/Open-Shell-Menu). It looks a little old but, if you want less telemetry...

> Duplicate of https://github.com/ChrisTitusTech/win10script/issues/289 and https://github.com/ChrisTitusTech/win10script/issues/293

True! Next time, search the issues page before opening it. Just a reminder @ChrisTitusTech, please add an issue/pr templete, that checks for duplicates...

The cause of your problems was probably a bad PR that Chris accepted. Shloud be fixed in a bit...

**Comment by micziz** [comment] 2022-03-20 08:27
Close this plz...

**Closed** 2022-06-13 15:33 UTC

**Comment by fgclue** [comment] 2022-06-18 17:55
-1 @micziz
