### ISSUE TITLE
Applying Essential Tweaks disables Background Apps

### ISSUE THREAD

**Issue by kAMENkitA** [ChrisTitusTech/win10script#170] opened 2021-08-18 06:09 UTC
HI Chris,
I did not know that applying Essential Tweaks disables B A's. I am aware that you put button for disabling B A who wants to do it.
I realised the issue when my MS Games started to crash or getting disconnected - I checked the BackGroundApps under Settings & saw they all are disabled.
Could you improve your script by removing that line with disabling B A under Essential tweaks?

Regards!

**Comment by ChrisTitusTech** [comment] 2021-08-19 14:22
Thanks for pointing this out. I think it was a bad pull request that put this in. I'll revert this to not touch background apps!

**Comment by kAMENkitA** [comment] 2021-08-20 10:03
Thank You Chris.
All the best.

**Comment by damian101** [comment] 2022-01-17 05:40
Another issue is caused by this: #253

**Comment by Carterpersall** [comment] 2022-03-22 02:14
@kAMENkitA if this issue is resolved, please close this issue to reduce clutter in the issues tab.

**Closed** 2022-03-22 07:41 UTC
